TGBOT-279 Add Jacoco, SonarCloud and checkstyle
Tutritp01/API-servise-TgBot pull request #10
Opened 2023-02-05 08:35 UTC by schneidervs

https://schneidervs.atlassian.net/browse/TGBOT-279

2023-02-05 16:59 UTC, yurasava submitted a review, later dismissed

2023-02-05 19:59 UTC, max-java requested changes
ptal

2023-02-05 19:59 UTC, max-java commented on .github/workflows/build.yml
> +      - name: Set up JDK 17
if we stay on v17, that should correspond in pom.xml 
Maybe 19?

2023-02-05 19:59 UTC, max-java commented on .github/workflows/build.yml
> +        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Tutritp01_API-servise-TgBot
ass new line

2023-02-05 19:59 UTC, max-java commented on .github/workflows/build.yml
> +        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Tutritp01_API-servise-TgBot
Is it possible to encrypt this key?

2023-02-05 19:59 UTC, max-java commented on build-tool/pom.xml
> +    <plugin>
add tab alignment

2023-02-05 19:59 UTC, max-java commented on build-tool/pom.xml
> +</project>
add new line

2023-02-05 19:59 UTC, max-java commented on build-tool/pom.xml
> +                <goals>
Should this work for every module ? Maybe move this to parent pom.

2023-02-05 19:59 UTC, max-java commented on build-tool/src/main/resources/config/checkstyle/checkstyle.xml
> +<?xml version="1.0"?>
add checking for empty line in the end of a file

2023-02-05 19:59 UTC, max-java commented on persistence-core/pom.xml
> -    <groupId>com.tutrit</groupId>
this change isn't related to issue 279

2023-02-05 19:59 UTC, max-java commented on pom.xml
> +        <module>build-tool</module>
I suggest use jacoco, sonar and checstyle for all module, there for adding build-tool in the scope of issue 279 redundant

2023-02-05 19:59 UTC, max-java commented on pom.xml
> +            <version>3.2.1</version>
all versions should be moved to properties

2023-02-05 19:59 UTC, max-java commented on pom.xml
> +                </plugin>
I don't think we need to fix versions for this plugins, don't we ?

2023-02-05 19:59 UTC, max-java commented on rest-api-service/pom.xml
> -    <packaging>pom</packaging>
this changes are not in the scope of #279 issue

2023-02-09 16:33 UTC, AlexanderYarokhovich submitted a review, later dismissed

2023-02-09 17:02 UTC, Artem-Metlushko submitted a review, later dismissed

2023-02-12 14:45 UTC, yurasava approved these changes

2023-02-12 14:45 UTC, max-java approved these changes
lgfm

2023-02-12 14:45 UTC, AlexanderYarokhovich submitted a review, later dismissed

2023-02-12 14:45 UTC, Sav4ykVladzislau submitted a review, later dismissed

2023-02-12 15:04 UTC, yurasava submitted a review, later dismissed

2023-02-12 15:24 UTC, Sav4ykVladzislau approved these changes

2023-02-13 15:36 UTC, yurasava approved these changes

2023-02-13 16:55 UTC, max-java approved these changes
let's merge it and see how it works

2023-02-13 16:55 UTC, max-java commented on integration/pom.xml
> +        <plugins>
I think that could be inherited from parent pom, isn't it?

2023-02-16 17:17 UTC, schneidervs commented on integration/pom.xml
> +        <plugins>
Yes

2023-02-19 09:57 UTC, Artem-Metlushko submitted a review, later dismissed

2023-02-19 09:57 UTC, AlexanderYarokhovich approved these changes

2023-02-19 12:08 UTC, Sav4ykVladzislau submitted a review, later dismissed

2023-02-19 12:24 UTC, Sav4ykVladzislau approved these changes

2023-02-19 12:24 UTC, max-java approved these changes
lgfm

2023-02-19 12:24 UTC, yurasava approved these changes

2023-02-19 12:25 UTC, AlexanderYarokhovich approved these changes

2023-02-19 12:25 UTC, Artem-Metlushko approved these changes

2023-02-19 12:25 UTC, merged