[WIP] TGBOT-279
Tutritp01/API-servise-TgBot pull request #18
Opened 2023-02-19 12:54 UTC by schneidervs

2023-02-19 13:11 UTC, schneidervs commented
Jacoco reports are not in the Sonar

2023-02-19 15:51 UTC, yurasava approved these changes

2023-02-23 07:44 UTC, max-java requested changes
ptal

2023-02-23 07:44 UTC, max-java commented on integration/pom.xml
> +                        <phase>package</phase>
I would not agree on this.
Tools like Sonar and Checkstyle are part of verifying phase, not package. 
we do packaging when everything is ok. 

What is the reason behind this changes?

2023-02-25 08:57 UTC, max-java commented
any updates on this?

2023-02-26 09:47 UTC, schneidervs commented on integration/pom.xml
> +                        <phase>package</phase>
Sonar won't get a coverage report until we correct all the deficiencies. To get a coverage report, but drop the project if there are errors.

2023-02-26 12:31 UTC, AlexanderYarokhovich approved these changes

2023-02-27 19:07 UTC, max-java approved these changes

2023-03-04 17:46 UTC, Sav4ykVladzislau approved these changes

2023-03-04 17:47 UTC, Artem-Metlushko approved these changes

2023-03-05 15:10 UTC, merged