[TGBOT-341] Add docker-compose.yml with mysql-db
Tutritp01/API-servise-TgBot pull request #29
Opened 2023-03-24 14:53 UTC by yurasava

https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-341

2023-03-25 14:06 UTC, Artem-Metlushko approved these changes

2023-03-26 11:27 UTC, max-java requested changes
ptal

2023-03-26 11:27 UTC, max-java commented on docker-compose.yml
> +services:
Have you tried to start that ? I think that would not run. there version part is necessary 

version: '3.3' 

https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee

2023-04-02 10:00 UTC, Sav4ykVladzislau approved these changes

2023-06-01 19:11 UTC, max-java commented
close as outdated

2023-06-01 19:11 UTC, closed without merging