[TGBOT-240] Extract in memory repository implementation in separate module
Tutritp01/API-servise-TgBot pull request #6
Opened 2023-02-04 21:47 UTC by Sav4ykVladzislau

https://schneidervs.atlassian.net/browse/TGBOT-240

2023-02-04 21:57 UTC, schneidervs approved these changes

2023-02-05 01:20 UTC, AlexanderYarokhovich approved these changes

2023-02-05 07:07 UTC, yurasava submitted a review, later dismissed

2023-02-05 08:05 UTC, Artem-Metlushko approved these changes

2023-02-05 09:23 UTC, schneidervs approved these changes

2023-02-05 17:06 UTC, yurasava submitted a review, later dismissed

2023-02-05 19:05 UTC, max-java requested changes
ptal

2023-02-05 19:05 UTC, max-java commented on persistence-core/src/main/java/com/tutrit/persistence/core/persistence/CarPersistence.java
> +    Car findById(String id);
I suggest to leave `carId` as a name for id

2023-02-05 19:05 UTC, max-java commented on persistence-core/src/main/java/com/tutrit/persistence/core/persistence/EngineerPersistence.java
> +    Engineer findById(String id);
I suggest engineerId as name for variable.

2023-02-07 20:47 UTC, schneidervs approved these changes

2023-02-07 20:47 UTC, schneidervs commented on rest-api-service/pom.xml
> +   </project>
This is unnecessary.

2023-02-08 14:54 UTC, yurasava approved these changes

2023-02-09 16:26 UTC, AlexanderYarokhovich approved these changes

2023-02-09 16:27 UTC, Artem-Metlushko submitted a review, later dismissed

2023-02-09 18:49 UTC, Sav4ykVladzislau commented on in-memory-repository/src/main/java/com/tutrit/persistence/InMemoryCarPersistence.java
> +    private static final List<Car> cars = new ArrayList<>();
To solve this problem, a task was created:
https://schneidervs.atlassian.net/browse/TGBOT-303

2023-02-09 18:49 UTC, Sav4ykVladzislau commented on in-memory-repository/src/main/java/com/tutrit/persistence/InMemoryCustomerPersistence.java
> +    private final static HashSet<Customer> customers = new HashSet<>();
To solve this problem, a task was created:
https://schneidervs.atlassian.net/browse/TGBOT-303

2023-02-12 14:51 UTC, max-java approved these changes
lgfm

2023-02-12 14:52 UTC, Sav4ykVladzislau commented on rest-api-service/pom.xml
> +
I remove this profile and i created task https://schneidervs.atlassian.net/browse/TGBOT-306

2023-02-12 16:58 UTC, yurasava approved these changes

2023-02-13 06:54 UTC, schneidervs approved these changes

2023-02-19 09:04 UTC, Artem-Metlushko approved these changes

2023-02-19 09:56 UTC, AlexanderYarokhovich submitted a review, later dismissed

2023-02-23 08:07 UTC, max-java commented
Please, rebase on main and squash.

2023-02-25 08:55 UTC, max-java approved these changes
I hope resolved discussions done properly , new changes lgfm. 
let's merge and see the result

2023-02-25 12:16 UTC, Artem-Metlushko approved these changes

2023-02-25 15:39 UTC, AlexanderYarokhovich approved these changes

2023-02-25 21:31 UTC, yurasava approved these changes

2023-02-26 09:49 UTC, schneidervs approved these changes

2023-02-26 10:04 UTC, merged