[TGBOT-242] Extract util module
Tutritp01/API-servise-TgBot pull request #7
Opened 2023-02-04 22:05 UTC by yurasava

https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-242

2023-02-05 01:13 UTC, AlexanderYarokhovich approved these changes
lgfm

2023-02-05 01:13 UTC, AlexanderYarokhovich commented on util/pom.xml
> +</project>
add empty line

2023-02-05 01:13 UTC, AlexanderYarokhovich commented on util/src/main/java/com/tutrit/Main.java
> +        System.out.println("Hello world!");
may be logger

2023-02-05 09:22 UTC, schneidervs submitted a review, later dismissed

2023-02-05 19:33 UTC, max-java requested changes
ptal

2023-02-05 19:33 UTC, max-java commented on util/pom.xml
> +    </properties>
take this from parent module, remove from this pom

2023-02-05 19:33 UTC, max-java commented on util/pom.xml
> +        </dependency>
add this to dependencyManagement of parent module, leave here only groupId and artifactId, 
and I think `<scope>` also could be removed

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/Main.java
> +}
This class could be removed

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/CarRepositoryToOurFormat.java
> +public class CarRepositoryToOurFormat {
That is one a hell of a naming )

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/CarRepositoryToOurFormat.java
> +public class CarRepositoryToOurFormat {
remove this class for now, this operations should be made by service and have proper tests. 
Let's cover this in the scope of a separate epic. 
please, create corresponding epic in jira

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/CarRepositoryToXml.java
> +    private static void saveOneUser(Car car, File directory) {
why `saveOneUser` works with cars ? isn't it a `saveOneCar` then? 
also, let's move this to a service in the scope of a new epic, the same one that we gona have for saving to 
proprietary format

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/CarRepositoryToOurFormat.java
> +    private CarRepositoryToOurFormat() {
proprietary format

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/CustomerRepositoryToOurFormat.java
> +public class CustomerRepositoryToOurFormat {
same here -move to epic

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/CustomerRepositoryToXml.java
> +public class CustomerRepositoryToXml {
same here - move to the epic

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/EngineerRepositoryToOurFormat.java
> +public class EngineerRepositoryToOurFormat {
same here - move to the epic

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/EngineerRepositoryToXml.java
> +public class EngineerRepositoryToXml {
same here - move to the epic

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/GetBodyAsMap.java
> +public class GetBodyAsMap {
`GetBodyAsMap` is a more method name rather than class method. 
I don't think we gona need this utility, so soggest to remove it

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/GetCommand.java
> +public class GetCommand {
one again - that is more method name rather than class. 

let's remove this, I doubt we gona need it

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/GetIdFromMap.java
> +public class GetIdFromMap {
same as above, remove

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/ParseMessage.java
> +    private static final Logger logger = Logger.getLogger(ParseMessage.class.getName());
use `@slf4j`from lombok

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/ParseMessage.java
> +    public static Message parseCommand(Request request, User user) throws ArrayIndexOutOfBoundsException {
all this converters should be replaced with `objectMapper` in the scope of separate issue. You can find example here. https://stackoverflow.com/questions/16428817/convert-a-mapstring-string-to-a-pojo
1. read string to map
2. use map as a source for convertValue
please, create jira issue.

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/ParseMessage.java
> +    private static final Logger logger = Logger.getLogger(ParseMessage.class.getName());
remove, to be resolved with objectMapper in separate issue, see below

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/ParsePromo.java
> +public class ParsePromo {
remove, use objectMapper

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/ParseUser.java
> +public class ParseUser {
remove, use objectMapper

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/UserRepositoryToOurFormat.java
> +public class UserRepositoryToOurFormat {
remove, to be resolved in the scope of a epic

2023-02-05 19:33 UTC, max-java commented on util/src/main/java/com/tutrit/util/UserRepositoryToXml.java
> +public class UserRepositoryToXml {
remove, to be resolve in the scope of the epic

2023-02-09 17:08 UTC, Sav4ykVladzislau approved these changes

2023-02-09 17:12 UTC, Artem-Metlushko approved these changes

2023-02-09 19:42 UTC, yurasava commented on util/src/main/java/com/tutrit/util/ParseMessage.java
> +    public static Message parseCommand(Request request, User user) throws ArrayIndexOutOfBoundsException {
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2/backlog?selectedIssue=TGBOT-305

2023-02-09 19:43 UTC, yurasava commented on util/src/main/java/com/tutrit/util/CarRepositoryToOurFormat.java
> +public class CarRepositoryToOurFormat {
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2/backlog?issueParent=10319

2023-02-12 08:35 UTC, schneidervs approved these changes

2023-02-12 14:47 UTC, max-java approved these changes
lgfm

2023-02-12 14:47 UTC, merged