[WIP][TGBOT-241] Extract file system repository implementation into separate module
Tutritp01/API-servise-TgBot pull request #8
Opened 2023-02-04 23:47 UTC by Sav4ykVladzislau

https://schneidervs.atlassian.net/browse/TGBOT-241

2023-02-05 07:09 UTC, yurasava approved these changes

2023-02-05 07:59 UTC, Artem-Metlushko submitted a review, later dismissed

2023-02-05 17:02 UTC, yurasava approved these changes

2023-02-05 19:44 UTC, max-java requested changes
There are confusing commits not related to fileSystem repo, please remove them.

2023-02-05 19:44 UTC, max-java commented on filesystem-repository/pom.xml
> +    </properties>
this should be moved in parent pom, please remove

2023-02-05 19:44 UTC, max-java commented on filesystem-repository/pom.xml
> +        </dependency>
make this managed dependency in parent pom

2023-02-05 19:44 UTC, max-java commented on filesystem-repository/pom.xml
> +            <artifactId>slf4j-api</artifactId>
we can use `slf4j` as transitive dependency from lombok

2023-02-05 19:44 UTC, max-java commented on filesystem-repository/src/main/java/com/tutrit/filesystem/persistence/FilesystemCarPersistence.java
> +        return null;
make custom `NotImplementedException` and throw it instead of returning null.

2023-02-05 19:44 UTC, max-java commented on in-memory-repository/pom.xml
> +        </dependency>
remove this, we can use `slf4j` from lombok

2023-02-05 19:44 UTC, max-java commented on in-memory-repository/src/main/java/com/tutrit/persistence/InMemoryCarPersistence.java
> +    public static final Logger logger = LoggerFactory.getLogger("CarPersistence logger");
use `@slf4j` instead

2023-02-05 19:44 UTC, max-java commented on in-memory-repository/src/main/java/com/tutrit/persistence/InMemoryCarPersistence.java
> +public class InMemoryCarPersistence implements CarPersistence {
Why `in memory` is at  `exctract file system implementation` task? 
I think that is a mistake in branching, revise this, please.

2023-02-05 19:44 UTC, max-java commented on rest-api-service/pom.xml
> +    </profiles>
this should go to integration module

2023-02-05 19:44 UTC, max-java requested changes
There are confusing commits not related to fileSystem repo, please remove them.

2023-02-09 16:28 UTC, Artem-Metlushko approved these changes

2023-02-09 16:30 UTC, AlexanderYarokhovich submitted a review, later dismissed

2023-02-12 08:35 UTC, schneidervs approved these changes

2023-02-13 06:54 UTC, schneidervs submitted a review, later dismissed

2023-02-13 16:47 UTC, Sav4ykVladzislau commented on filesystem-repository/src/main/java/com/tutrit/filesystem/persistence/FilesystemCarPersistence.java
> +        return null;
I created customer exception and throw it

2023-02-13 16:49 UTC, Sav4ykVladzislau commented on filesystem-repository/pom.xml
> +            <artifactId>slf4j-api</artifactId>
I use lombok for these purposes

2023-02-13 16:50 UTC, Sav4ykVladzislau commented on filesystem-repository/pom.xml
> +    </properties>
I move this properties in parent pom

2023-02-13 16:50 UTC, Sav4ykVladzislau commented on filesystem-repository/pom.xml
> +        </dependency>
i move this dependency in parent pom

2023-02-13 16:51 UTC, Sav4ykVladzislau commented on in-memory-repository/pom.xml
> +        </dependency>
I remove this dependency

2023-02-13 16:54 UTC, Sav4ykVladzislau commented on rest-api-service/pom.xml
> +    </profiles>
I remove this profile and i created task https://schneidervs.atlassian.net/browse/TGBOT-306

2023-02-16 17:23 UTC, schneidervs submitted a review, later dismissed

2023-02-16 17:23 UTC, schneidervs commented on filesystem-repository/src/main/java/com/tutrit/filesystem/persistence/NotImplementedException.java
> +}
No new line

2023-02-19 09:06 UTC, Artem-Metlushko submitted a review, later dismissed

2023-02-19 09:35 UTC, yurasava submitted a review, later dismissed

2023-02-19 09:57 UTC, AlexanderYarokhovich submitted a review, later dismissed

2023-02-23 08:02 UTC, max-java commented
Please, rebase on main branch

2023-02-25 08:56 UTC, max-java commented
any updates on this?

2023-02-26 15:57 UTC, merged